# Generated by Django 4.1 on 2023-09-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_alter_image_id_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelTable(
            name='image',
            table='external_image',
        ),
    ]
