# Generated by Django 4.1 on 2023-09-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Image", "0003_alter_image_options_alter_image_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
