version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.10-bullseye
    volumes:
      - .:/workspace
    command: sleep infinity
    ports:
      - 8080:8080

  db:
    image: soulteary/milvus:embed-2.1.0
    restart: unless-stopped
    ports:
      - 19530:19530